Open-IoT-Service-Platform/platform-launcher

- Makefile
- docker-compose.yml
Makefile puts keys into data/keys/ssl
docker-compose.yml lets nginx mount data/keys/ssl to /etc/ssl
Attention: A parallel PR is needed in oisp-frontend to add this path to default.conf in nginx module
> Makefile, docker-comopose.yml: Added SSL self signed certificate

- Makefile
`distclean` has to be run before `update`, because:
1. otherwise container cannot be stopped as the config script is missing.
2. init should be rerun after updates.
> MAKEFILE: Force distclean before update

- docker-compose.yml
The volume is no longer required as the source is moved into the container.
> Remove volume mount from websocket-server

- Makefile
Added .init to start to make sure it works properly after using test. Using start after test was giving public.pem is not existing error.
> Add .init to make start

- Makefile
ifconfig is deprecated (actually since 2012) and replaced by ip. Ubuntu 18.04 does not include ifconfig by default, but does have ip, like many other modern distros.
> Moved from ifconfig to ip in Makefile

- Makefile
- docker-compose.yml
- docker-debugger/Dockerfile
- docker-debugger/README.md
- docker-debugger/docker-compose-debugger.yml
I have been using this container a lot myself for debugging, and I am planning to base the Kubernetes tests on a container, and I thought it might be useful to others too. We could also add an option to run the e2e tests in a container inside the OISP and/or a different docker network. 
Do you think it is a good idea to include it by default in docker-compose? It is not supposed to be deployed in production, but docker-compose is mainly our development platform anyway.
> Created a new container for debugging [DISCUSSION]

- docker-debugger/Dockerfile
Upgrade to Ubuntu 18.04 and install tools needed for load testing with locust.
> Updated debugger container image

- Makefile
- docker-compose.yml
Setting DISABLE_RATE_LIMITS=true will now disable the rate limits security check at frontend. Should be committed with [#75](https://github.com/Open-IoT-Service-Platform/oisp-frontend/pull/75).
> Add option DISABLE_RATE_LIMITS to Makefile for frontend

- tests/Makefile
After Jaeger agent container has been added to k8s (for monitoring) there are multiple
containers in the frontend, and it is necessary to specify that the test command
should run in 'dashboard'
> tests/Makefile: Adapt k8s tests

- setup-environment.example.sh
This should close #120
Some variables remain, but it would be too much effort to update other containers to read them, or sometimes create a container instead of a standard container just for the purpose. I think it should be enough for now when we can see which variables are used by docker-compose/other scripts.
> setup-environment.example.sh: Remove unnecessary exports

- tests/Makefile
This is needed for executing automated e2e testing, because when the test is executed in a script, the -i switch is creating problems because it tries to connect to stdio
> tests/Makefile: Removed -i switch from docker

- .circleci/config.yml
* Changed PUSH_DRYRUN behavior. If it is set, there will be no real push
* Pushing the renamed images with docker directly instead with docker-compose
> CircleCI update

- Makefile
- docker-postgres/Dockerfile
This reverts commit 749c529deb1f3e6a487d7c0555d46a739ce863f5.
Until the sequelize table creation problem at frontend is solved, *.sql files must be copied back.
> Revert "Postgres: Do not copy *.sql files"

- .gitmodules
> beam-rule-engine: Update submodule URL to use HTTPS instead of GIT

- tests/subtests/mqtt-data-sending-tests.js
> mqtt-subtests: give the backend 1s more time to synchronize

- kubernetes/.gitignore
- kubernetes/util/.gitignore
- kubernetes/util/proxy_service_to_localhost.py
In order to run a service on localhost, 3 steps should be taken:
1. Run this script to replace the k8s service to proxy requests to localhost
2. Run kubefwd to allow localhost access k8s services
3. Import environment varianles and files such as keys from k8s.
> k8s/util: Added script to run service on localhost

- docs/conf.py
This was tested on my fork with automated build on https://oisp-wip.readthedocs.org
> docs: Minor config change to enable autobuild on readthedocs.org

- .circleci/config.yml
- Makefile
- docker-compose.yml
- docker/opentsdb/Dockerfile
- docker/postgres/Dockerfile
- kubernetes/Makefile
- kubernetes/values.yaml
Also modified opentsdb to speed up build by removing the update, which is performed while building the parent image (hbase) and unified some layers.
> Refactoring: simplified docker-compose.yaml to be used for builds only.

- docs/usage/quickstart.rst
- kubernetes/cert-manager/certificate_web_prod.yaml
- kubernetes/cert-manager/clusterissuer-prod.yaml
- kubernetes/templates/frontend.yaml
- kubernetes/templates/ingress.yaml
- kubernetes/templates/websocket-server.yaml
- kubernetes/values.yaml
* frontend and websoket-server have now same http and https ingres to allow to create joint letsencrypt certificates
* provided templates for automated cert-management
> Change in Ingress to allow automated cert-management

- tests/lib/helpers/rules.js
Rule test assumed Automatic resetType rule but configured Manual resetType. Until now there was no difference in Alert behaviour but in future the Alert module will react differently to Manual resetType.
> Fixed wrong rule configuration in e2e test:

- Makefile
- kubernetes/templates/configmaps/oisp-config.yaml
- kubernetes/templates/frontend.yaml
- kubernetes/templates/grafana.yaml
- kubernetes/templates/jobs/db_setup.yaml
- kubernetes/templates/jobs/db_update.yaml
- tests/Makefile
- tests/test-config-template.json
This was done in order to remove the ambiguity, as both were used interchangably, which is problematic for the plans of seperating them into two microservices.
> Rename dashboard to frontend

- docker/opentsdb/scripts/tsdb-startup.sh
The flush intervall has been reduced to 100ms.
> Low latency patch for OpenTSDB

- util/restart-cluster.sh
The new images included in upstream are not stable. Since they have no release containing docker-compose yet, we should stay fixed to a commit, until a tagged release arrives.
> Fixed k3s version again

- Makefile
NAMESPACE had to be specified during deployment, instead of hardcoding oisp.
timeout has been set to 600 from the 300 default, as deployments takes a long time
when resources are scarce.
> CI test fix/stability: Fix namespace & timeout.

- Makefile
- kubernetes/templates/frontend.yaml
- kubernetes/templates/hbase-master.yaml
- kubernetes/templates/hbase-region.yaml
- kubernetes/templates/hdfs-datanode.yaml
- kubernetes/templates/jobs/db_setup.yaml
- kubernetes/templates/jobs/db_update.yaml
- kubernetes/values.yaml
- tests/Makefile
- tests/oisp-tests.js
* Changed dependencies of dbsetup/dbupdate, keycloak and frontend. These jobs/pods created the 10min waiting time when helm chart
was installed. Instea
* Removed db and keycloak reset since this does not bring any advantage for test but created race condition with rule-enging token
* Reduced number of hbase and minio containers to minimum
* Added wait for debugger container
* Increased timeouts for authentication
> Helm and setup dependencies changed to speedup helm deployments

- Makefile
- kubernetes/templates/hbase-master.yaml
- kubernetes/templates/websocket-server.yaml
- tests/oisp-tests.js
- tests/subtests/data-sending-tests.js
- tests/subtests/mqtt-data-sending-tests.js
* Added keycloak reset to reset-db target
* Cleaned up helm templates of hbase-master and websocket-server
* Increased timeouts for backend. Due to new kafka-centric, there is no delay
when frontend sends data and thus, backend gets more time for processing and
returning data
> Clean up and adjustment of delays for new backend

- util/restart-cluster.sh
> Quickfix: removed wrong link for prometheus setup in Kafka-cluster

- kubernetes/templates/mqtt.yaml
- util/get_oisp_credentials.sh
* Fixed problem when reading out secrets during upgrade: jq does not accept dashes in field names and needs thus proper masking
> * Changed MQTT Service to Headeless to support better loadbalancing

- .circleci/config.yml
The tests have passed: https://circleci.com/gh/Open-IoT-Service-Platform/platform-launcher/1087
Something with git integration seems to be off, it still shows a red cross.
Apart from a race condition in rule engine this seems to work stably. 
The branch is created on this repository to test the CI with the same configuration and will be deleted after merging.
> Ci feature (Keycloak values overwrite)
