Open-IoT-Service-Platform/platform-launcher

README.md
Shell commands were started with # even though they are not required to run as root. Changed those to $ signs.
=> Updated README (#s to $s for non-root commands)

Makefile
This is necessary because feature and topic branches which are also used for development should not update submodules automatically.
=> Prevent all non master branches from automatically updating submodules

Makefile, docker-compose-quick.yml
This adds the command start-quick, which pulls the images from dockerhub.streammyiot.com (login required)
=> Added docker registry push and start-quick/build-quick

tests/Makefile
This is necessary because the reset command goes through frontend.
=> Wait for frontend to come up before attempting to reset DB

docker-compose.yml, setup-environment.example.sh
Only to be merged with the parallel request in rules-engine repo.
=> Merge Gearpump and rules-engine containers in multistep-build.

.gitignore, Makefile, config-backup/README.md
Also added some file to .gitignore.
=> Automatically remove default config after make update

Makefile, docker-compose-quick.yml, docker-compose.yml, docker-postgres/Dockerfile
Please do not merge yet. Further changes may be added to this PR.
=> Changes to postgres container.

.gitignore, Makefile, tests/Makefile, tests/oisp-tests.js, tests/test-config-docker.json, tests/test-config-kubernetes.json
Test platform can be chosen by setting the `TESTING_PLATFORM` variable, defaults to `docker` (alt: `kubernetes`)
=> Test kubernetes premerge

tests/lib/helpers/data.js, tests/oisp-tests.js, tests/subtests/data-sending-tests.js, tests/subtests/promise-wrap.js
* Added subtests which send and receive data
* Extended API for GPS and attribute handling
* Extended API for specifying additional target filters
* Extended searchDataAdvanced to request and receive attributes
* Tests for sending aggretated metrics for several components in one request
=> Created Data Sending subtests and necessary API in helper library

.gitmodules, Makefile, docker-compose.yml, setup-environment.example.sh
* Added oisp-mqtt-gw submodule,
* Adapted to OISP config structure and added to setup-environment.sh
* Added broker and gateway to main docker-compose
* Added cafile, certfile, etc to broker config.
=> MQTT integration:

setup-environment.example.sh
=> Added backend config for jaeger

docker-debugger/Dockerfile
=> debugger: Include apache2-utils and ipython

docker-debugger/Dockerfile, docker-debugger/load-tests/create_test.py
=> debugger: Add load test creator util.

.circleci/config.yml, Makefile
=> Build and E2E Test implemented for CircleCi environment

docker-compose.yml
=> docker-compose.yml: Added tag to singularities/hadoop image

docker-compose.yml
=> docker-compose.yml: Added tags for MQTT containers and Hadoop Datanode

Makefile, docker-postgres/Dockerfile
Makefile: Fix TEST environment variable to use test database
=> Postgres: Do not copy *.sql files

Makefile, docker-postgres/Dockerfile
=> Postgres: copy all .sh files, Makefile: Fix unselected test database bug

docker-postgres/Dockerfile
@wagmarcel this should be merged after #156 , I will rebase this PR after you merged it
=> Postgres: Don't copy .sql scripts

tests/oisp-tests.js, tests/package.json, tests/subtests/grafana-tests.js, tests/test-config-docker.json, tests/test-config-kubernetes.json
=> Added grafana subtests

tests/lib/helpers/data.js, tests/oisp-tests.js, tests/package.json, tests/subtests/data-sending-tests.js
* Adding all 4 data types for tests
* Testing aggreation of different components in one data submission
* Testing adding location information and attributes to all data types
* Updating sdk git hash to use latest fix for binary data sending
* Updaing test library to handle binary data
* Updated submodule references
=> data-sending-subtests: closes #161

tests/lib/helpers/devices.js, tests/oisp-tests.js, tests/subtests/device-activation-tests.js, tests/subtests/promise-wrap.js
=> Added device activation subtests

.gitmodules, docker-compose.yml
=> Bye Bye Gearpump - Welcome Apache Beam and Flink for the rule-engine

docker-debugger/Dockerfile
Imagemagick is required for the tests.
=> debugger: Add imagemagick

.circleci/config.yml, kubernetes/templates/minio.yaml, kubernetes/util/build-and-import-images.sh, kubernetes/util/import-images.sh
=> .circleci: Moved tests to kubernetes

Makefile, kubernetes/templates/hbase-master.yaml, kubernetes/templates/hbase-region.yaml, kubernetes/templates/hdfs-namenode.yaml
=> kubernetes: Fix hbase config & extend Makefile helm options.

util/get_oisp_container_config.sh
=> Added util tool: get_oisp_container_config.sh

tests/lib/helpers/auth.js, tests/oisp-tests.js, tests/package.json, tests/subtests/promise-wrap.js, tests/subtests/refresh-token-tests.js
=> Added refresh token subtests

.circleci/config.yml, Makefile, ci_deployer/Dockerfile, ci_deployer/README.md, ci_deployer/deploy.sh
=> CircleCI for deployment.

.circleci/config.yml, ci_deployer/deploy.sh
=> Circleci: Added auth for deployer container

Makefile, kubernetes/templates/test/debugger.yaml, tests/Makefile
=> kubernetes: Allow different namespaces then oisp.

docs/development/developers_guide.rst
=> Added examples for local deployments for development guide

Makefile, kubernetes/templates/configmaps/oisp-config.yaml, kubernetes/values.yaml
This is preperation for autogeneraiton of random credentials.
=> kubernetes: Move authentication config to values.yaml

kubernetes/templates/jobs/db_update.yaml
=> Introducing Helm Hooks to manage DB creation and updates

Makefile, docker/debugger/Dockerfile, kubernetes/templates/configmaps/oisp-config.yaml, kubernetes/templates/test/debugger.yaml, kubernetes/values.yaml, tests/Makefile, tests/test-config-template.json, util/get_oisp_credentials.sh, util/setup-ubuntu18.04.sh
=> Automatically generate passwords during deployment.

tests/subtests/timebased-rule-tests.js
=> Fix: Timebased Rule test - delete all four Alerts

Makefile, docs/usage/quickstart.rst, kubernetes/iot-agent/deploy-testsensor/create.sh, kubernetes/iot-agent/deploy-testsensor/deployment.yaml, kubernetes/iot-agent/deploy-testsensor/pvc.yaml, kubernetes/iot-agent/deploy-testsensor/sensorSpecs.json, kubernetes/iot-agent/global-config/activation-code, kubernetes/iot-agent/global-config/config.json, kubernetes/iot-agent/global-config/create.sh
=> Added IoT Agent testsensor K8s support

ci_deployer/Dockerfile, ci_deployer/deploy.sh, util/get_oisp_credentials.sh
Dependencies have been added to deployer container, the script has been updated to check for exact matches in helm chart name.
=> Fix CI deployment

kubernetes/templates/configmaps/oisp-config.yaml, kubernetes/templates/ruleengine.yaml, kubernetes/values.yaml
=> Rename gearpump to rule-engine.

kubernetes/ThirdPartyLicenses.txt, kubernetes/charts/stolon/templates/keeper-statefulset.yaml, kubernetes/charts/stolon/templates/proxy-deploy.yaml, kubernetes/charts/stolon/templates/sentinel-deploy.yaml, kubernetes/templates/test/debugger.yaml, util/restart-cluster.sh
=> Updates for Kubernetes 1.16

kubernetes/cert-manager/certificate_web_prod.yaml
=> Updated Certificate to match secret of ingress

util/restart-cluster.sh
=> Quickfix [Helm]: Fix version to 2.16

Makefile, kubernetes/templates/hbase-region.yaml, kubernetes/templates/redis.yaml, util/restart-cluster.sh, util/setup-ubuntu18.04.sh
Helm installation has been moved to host setup, as Helm3 does not have a cluster component (tiller) anymore.
=> Upgraded to Helm 3

docker/hbase/scripts/entrypoint-region.sh, docker/hbase/scripts/entrypoint.sh, kubernetes/.helmignore, kubernetes/templates/configmaps/hdfs-config.yaml, kubernetes/templates/hbase-master.yaml, kubernetes/templates/hbase-region.yaml, kubernetes/templates/hdfs-datanode.yaml, kubernetes/values.yaml
=> Extend number of RegionServers and HDFS-Datanodes to 3

kubernetes/templates/minio.yaml, kubernetes/values.yaml
=> Minio replica set to 2 for non-resource-limited deployment

kubernetes/values.yaml
=> Minio needs at least 4 insances for cluster mode

kubernetes/templates/configmaps/oisp-config.yaml, kubernetes/templates/kafkacluster.yaml, kubernetes/values.yaml, tests/test-config-template.json
=> Changes of Kafka config to allow backend sending larger data

kubernetes/cert-manager/certificate_web_prod.yaml, kubernetes/cert-manager/clusterissuer-prod.yaml, kubernetes/templates/ingress.yaml, kubernetes/values.yaml
=> Ingress and Cert-Manager update to work with nginx and new oisp.info url

Makefile, keycloak/oisp-realm.json, kubernetes/templates/configmaps/oisp-config.yaml, kubernetes/templates/mqtt.yaml, kubernetes/values.yaml, util/get_oisp_credentials.sh
* mqtt-broker is now client in OISP realm
Prepare Kafka update for MQTT
=> MQTT Keycloak integration

kubernetes/values.yaml
=> Increased Kafka resource requests to make sure it will be priorized

.circleci/config.yml, Makefile, kubernetes/templates/backend.yaml, kubernetes/templates/cassandra-cluster.yaml, kubernetes/templates/configmaps/oisp-config.yaml, kubernetes/templates/frontend.yaml, kubernetes/templates/grafana.yaml, kubernetes/templates/jobs/db_setup.yaml, kubernetes/templates/jobs/db_update.yaml, kubernetes/templates/kairosdb.yaml, kubernetes/templates/mqtt.yaml, kubernetes/templates/ruleengine.yaml, kubernetes/templates/test/debugger.yaml, kubernetes/templates/websocket-server.yaml, kubernetes/values.yaml
Do not merge yet, documentation (and eventually minor changes) pending.
=> Ci over ssh

Makefile, tests/Makefile, tests/oisp-prep-only.js
=> Revived oisp-prep-only target in Makefile. Needed for iot-agent tests.

kubernetes/values.yaml
=> Set kafka retention policy to 1d

kubernetes/values.yaml
=> Added docker credentials to keycloak config

.gitignore, docker/rule-engine-deployer/Dockerfile, docker/rule-engine-deployer/app.py, docker/rule-engine-deployer/requirements.txt, kubernetes/Chart.yaml, kubernetes/ThirdPartyLicenses.txt, kubernetes/templates/configmaps/oisp-config.yaml, kubernetes/templates/flink/flink-configuration-configmap.yaml, kubernetes/templates/flink/jobmanager-deployment.yaml, kubernetes/templates/flink/jobmanager-rest-service.yaml, kubernetes/templates/flink/jobmanager-service.yaml, kubernetes/templates/flink/taskmanager-deployment.yaml, kubernetes/templates/jobs/ruleengine.yaml, kubernetes/templates/kairosdb.yaml, kubernetes/templates/mqtt.yaml, kubernetes/templates/test/debugger.yaml, kubernetes/values.yaml, package-lock.json
Temporarily using image from arkocal/rule-engine-deployer.
=> rule-engine: Add a flink cluster inside OISP and run rule-engine inside.

kubernetes/values.yaml
=> enable JMX in Kafka to get statistics of brokers

kubernetes/templates/kairosdb.yaml, util/deploy_operators.sh
=> Added Liveprobe for kairosdb

kubernetes/templates/jobs/ruleengine.yaml
=> Finalize rule engine deployment as job by updating template.
